In [ ]:
import diffolars.diff as dd
from diffolars.demo import get_df_pair

In [ ]:
dfs = get_df_pair(10, 10, n_new_cols=5, n_new_rows=5)
o = dfs['original']
m = dfs['mutated']

Generating initial dataset with 10 rows and 10 columns.
Generated mutated dataset.

In [ ]:
dd.column_intercept(o, m)

{'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str',
 'record_id'}

In [ ]:
dd.report_prune(o, m)

{'date_pruned': datetime.datetime(2026, 7, 2, 22, 20, 10, 228390),
 'cols_only_in_prev': 'No exclusives',
 'num_rows_only_in_prev': 0,
 'cols_only_in_next': 'col_10_int , col_12_float , col_14_int , col_13_datetime , col_11_str',
 'num_rows_only_in_next': 5}

In [ ]:
dd.prune_rows(o, m)

shape: (5, 3)
┌────────────────────────────┬──────────────┬─────────────────────────────────┐
│ date_pruned                ┆ source_table ┆ record_id                       │
│ ---                        ┆ ---          ┆ ---                             │
│ datetime[μs]               ┆ str          ┆ str                             │
╞════════════════════════════╪══════════════╪═════════════════════════════════╡
│ 2026-07-02 22:20:10.239302 ┆ next_table   ┆ eaed400f-bf84-4e9a-8e18-eb58bb… │
│ 2026-07-02 22:20:10.239302 ┆ next_table   ┆ 74992ba7-6c8f-45ed-bc01-b23da7… │
│ 2026-07-02 22:20:10.239302 ┆ next_table   ┆ 2cbecc5c-122d-4dfa-89ce-0d26b3… │
│ 2026-07-02 22:20:10.239302 ┆ next_table   ┆ b71fc509-df19-43c0-a921-deb90d… │
│ 2026-07-02 22:20:10.239302 ┆ next_table   ┆ 2fab05df-423b-43c9-999b-3ca228… │
└────────────────────────────┴──────────────┴─────────────────────────────────┘

In [ ]:
csd=dd.column_symmetric_diff(o, m)
csd

{'prev': set(),
 'next': {'col_10_int',
  'col_11_str',
  'col_12_float',
  'col_13_datetime',
  'col_14_int'}}

In [ ]:
dd.row_intercept(o, m)

{'0381f42e-dfda-4189-b98c-491f5be3fdd7',
 '041a1c01-c81b-4dc3-a7d3-cd0431c14190',
 '58d6abf1-8ac0-44e5-a57c-2089599a6c8e',
 '5c056bd3-2d17-48f4-bd4d-49d19f3fa78b',
 '6b9693af-0ec3-4178-99dc-d75c61f3166a',
 'a8324415-a54c-4375-a153-6dd479eddbd8',
 'abf91cb6-e468-457b-b5c0-871dab639d76',
 'b3781220-43d5-4e3e-a86c-0f0d4bbc6f2a',
 'cda74e65-7240-453b-bc8b-bdbb6b6c9f6a',
 'f514057e-5ec0-45d4-9bac-e76615d666fd'}

In [ ]:
dd.row_symmetric_diff(o, m)

{'prev': set(),
 'next': {'2cbecc5c-122d-4dfa-89ce-0d26b36be771',
  '2fab05df-423b-43c9-999b-3ca228a7990a',
  '74992ba7-6c8f-45ed-bc01-b23da79076e7',
  'b71fc509-df19-43c0-a921-deb90de6dfeb',
  'eaed400f-bf84-4e9a-8e18-eb58bb142a34'}}

In [ ]:
dd.get_cols(o)[1]

'col_0_int'

In [ ]:
# from polars.testing import assert_frame_equal

# # Raises an AssertionError if they are not identical
# assert_frame_equal(o, m, check_dtype=True)

In [ ]:
edf = m.join(o, how="anti", on="record_id")
edf

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ col_0_int ┆ col_1_str ┆ col_2_flo ┆ … ┆ col_11_st ┆ col_12_fl ┆ col_13_da ┆ col_14_i │
│ ---       ┆ ---       ┆ ---       ┆ at        ┆   ┆ r         ┆ oat       ┆ tetime    ┆ nt       │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ str       ┆ f64       ┆ datetime[ ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ μs]       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ eaed400f- ┆ -539459   ┆ yiSeXruxR ┆ 958619.18 ┆ … ┆ XNADoWUnc ┆ 286504.81 ┆ 2021-06-0 ┆ 203314   │
│ bf84-4e9a ┆           ┆ e         ┆ 1035      ┆   ┆ f         ┆ 4206      ┆ 7         ┆          │
│ -8e18-eb5 ┆           ┆           ┆           ┆   ┆           ┆           ┆ 23:29:26  ┆          │
│ 8bb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 74992ba7- ┆ 478480    ┆ OLUtErdJH ┆ -553402.7 ┆ … ┆ bMiUFtqyY ┆ -982715.0 ┆ 2024-09-0 ┆ 16869    │
│ 6c8f-45ed ┆           ┆ x         ┆ 45696     ┆   ┆ U         ┆ 09284     ┆ 4         ┆          │
│ -bc01-b23 ┆           ┆           ┆           ┆   ┆           ┆           ┆ 10:07:28  ┆          │
│ da7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2cbecc5c- ┆ 458582    ┆ nneCKfFZn ┆ 574002.17 ┆ … ┆ BTqbkWrfG ┆ -502279.8 ┆ 2000-12-0 ┆ 921427   │
│ 122d-4dfa ┆           ┆ m         ┆ 9714      ┆   ┆ h         ┆ 83733     ┆ 5         ┆          │
│ -89ce-0d2 ┆           ┆           ┆           ┆   ┆           ┆           ┆ 18:35:28  ┆          │
│ 6b3…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b71fc509- ┆ -371353   ┆ mHSYGAQiR ┆ -630210.7 ┆ … ┆ VqECfjkvY ┆ 325642.72 ┆ 2000-05-0 ┆ 686750   │
│ df19-43c0 ┆           ┆ c         ┆ 24765     ┆   ┆ p         ┆ 2194      ┆ 6         ┆          │
│ -a921-deb ┆           ┆           ┆           ┆   ┆           ┆           ┆ 13:12:17  ┆          │
│ 90d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2fab05df- ┆ -596066   ┆ SmQUKcxlr ┆ 69068.101 ┆ … ┆ IGxSOtyMQ ┆ -780488.1 ┆ 2024-10-1 ┆ -717673  │
│ 423b-43c9 ┆           ┆ Q         ┆ 024       ┆   ┆ m         ┆ 09978     ┆ 1         ┆          │
│ -999b-3ca ┆           ┆           ┆           ┆   ┆           ┆           ┆ 16:26:59  ┆          │
│ 228…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘