# Import our functions to test

In [2]:
import diffolars.diff as dd
from diffolars.demo import get_df_pair
import polars as pl

# Testing the core usage here:

In [11]:
# Example Usage:

# Get example original and mutated dataframe pair
dfs = get_df_pair(10, 10, n_new_cols=5, n_new_rows=5, coverage=0.5)
o = dfs['original']
m = dfs['mutated']




prune_record = dd.report_prune(o, m)

pruned_df = dd.pruned_rows(o, m)

result_df = dd.bitdiff(o, m)

print("\n")
print(pl.DataFrame(prune_record))
print(pruned_df)
result_df

Generating initial dataset with 10 rows and 10 columns.
Generated mutated dataset.
Found 0 rows unique to the current (original) table.
Found 5 rows unique to the next (latest) table.


shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ date_pruned       ┆ cols_only_in_prev ┆ num_rows_only_in_ ┆ cols_only_in_late ┆ num_rows_only_in │
│ ---               ┆ _load             ┆ prev_load         ┆ st_load           ┆ _latest_load     │
│ datetime[μs]      ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│                   ┆ str               ┆ i64               ┆ str               ┆ i64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 2026-07-03        ┆ No exclusives     ┆ 0                 ┆ col_12_float ,    ┆ 5                │
│ 21:00:55.439842   ┆                   ┆                   ┆ col_14_int , co…  ┆                  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘
shape: (5, 3)
┌────────────────────────────┬─────────────────┬─────────────────────────────────┐
│ date_pruned                ┆ source_dataload ┆ record_id                       │
│ ---                        ┆ ---             ┆ ---                             │
│ datetime[μs]               ┆ str             ┆ str                             │
╞════════════════════════════╪═════════════════╪═════════════════════════════════╡
│ 2026-07-03 21:00:55.441315 ┆ latest load     ┆ 9b8ee98d-eac3-4913-a2c0-ab089b… │
│ 2026-07-03 21:00:55.441315 ┆ latest load     ┆ 0674f6d8-bd1c-4fac-9df5-37b1cd… │
│ 2026-07-03 21:00:55.441315 ┆ latest load     ┆ de8c05da-78de-47a8-ae75-61d5d4… │
│ 2026-07-03 21:00:55.441315 ┆ latest load     ┆ 7b13d5e0-5079-43c6-b604-7145d3… │
│ 2026-07-03 21:00:55.441315 ┆ latest load     ┆ d1ac0a12-c88a-4e55-aeb5-501294… │
└────────────────────────────┴─────────────────┴─────────────────────────────────┘

shape: (10, 2)
┌─────────────────────────────────┬───────────────┐
│ record_id                       ┆ diff_bitarray │
│ ---                             ┆ ---           │
│ str                             ┆ u64           │
╞═════════════════════════════════╪═══════════════╡
│ 2bc1ac8e-032b-4b7e-ab4d-508197… ┆ 229           │
│ 1032a479-7dfb-4f6d-9a56-f90447… ┆ 442           │
│ 6a5fba80-b9ce-47a3-93c0-b4f491… ┆ 888           │
│ 3ad7f100-1142-4511-afd3-7cef26… ┆ 772           │
│ a614403b-9de6-4bb6-90f3-44983e… ┆ 290           │
│ b49601e9-643d-467e-a5d2-927333… ┆ 155           │
│ 34c9b7fe-c9a7-4b5c-92d0-7cd95b… ┆ 645           │
│ 6150cfb8-7d1f-4bca-85ad-be4995… ┆ 121           │
│ 888ad089-d4da-4ffd-a83c-43ac07… ┆ 1022          │
│ b4ecf81b-e68d-49d3-b17f-fbd117… ┆ 354           │
└─────────────────────────────────┴───────────────┘

In [ ]:
print(bin(199))
dd.brian_kernighan(199)

0b11000111

5

# Checking other functionalities by themselves...

In [ ]:
# Here, we get the core tables:
oc, mc = dd.get_core(o, m)
print(oc.head(5))
print(mc.head(5))

In [ ]:
dd.column_intercept(o, m)

{'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str',
 'record_id'}

In [ ]:
dd.report_prune(o, m)

{'date_pruned': datetime.datetime(2026, 7, 3, 20, 44, 55, 782766),
 'cols_only_in_prev_load': 'No exclusives',
 'num_rows_only_in_prev_load': 0,
 'cols_only_in_latest_load': 'col_12_float , col_13_datetime , col_11_str , col_10_int , col_14_int',
 'num_rows_only_in_latest_load': 5}

In [ ]:
dd.pruned_rows(o, m)

Found 0 rows unique to the current (original) table.
Found 5 rows unique to the next (latest) table.

shape: (5, 3)
┌────────────────────────────┬─────────────────┬─────────────────────────────────┐
│ date_pruned                ┆ source_dataload ┆ record_id                       │
│ ---                        ┆ ---             ┆ ---                             │
│ datetime[μs]               ┆ str             ┆ str                             │
╞════════════════════════════╪═════════════════╪═════════════════════════════════╡
│ 2026-07-03 20:44:55.793078 ┆ latest load     ┆ 8ac23cf2-ed78-4cec-9c86-57d9d8… │
│ 2026-07-03 20:44:55.793078 ┆ latest load     ┆ c308b1f5-6893-4da6-85ae-222cab… │
│ 2026-07-03 20:44:55.793078 ┆ latest load     ┆ 4d52173d-ab77-461c-ab70-613253… │
│ 2026-07-03 20:44:55.793078 ┆ latest load     ┆ 5d0e0eb7-eae7-4dab-b106-30c07a… │
│ 2026-07-03 20:44:55.793078 ┆ latest load     ┆ 5e8d729a-e39b-41d6-9625-fbd62a… │
└────────────────────────────┴─────────────────┴─────────────────────────────────┘

In [ ]:
csd=dd.column_symmetric_diff(o, m)
csd

{'prev_load': set(),
 'latest_load': {'col_10_int',
  'col_11_str',
  'col_12_float',
  'col_13_datetime',
  'col_14_int'}}

In [ ]:
dd.row_intercept(o, m)

{'0da898f1-1837-466d-a536-59ebe57f9525',
 '3049fae3-a8ce-455a-9ed5-fd5f301e80ca',
 '5740a46d-1bc1-4019-9250-e2af7e25b4bc',
 '6f4c18c0-d103-4d0e-94ce-dadb5dd979bc',
 '8a2f3879-e94a-44e3-bc0e-f5b3e252b91d',
 '8de32b0b-ac43-48a0-b48f-7e1587d435bc',
 'c89894bb-3be4-4142-b1ef-468669491e59',
 'dcfb2fc3-e69d-47fc-aa3a-1bc57014b7b2',
 'dd23089e-f6cc-4661-b9b4-ddf9a2e64dd8',
 'e66bc8dc-0df1-49df-a260-451c000333d4'}

In [ ]:
dd.row_symmetric_diff(o, m)

{'prev_load': set(),
 'latest_load': {'4d52173d-ab77-461c-ab70-613253b8bd62',
  '5d0e0eb7-eae7-4dab-b106-30c07afb3760',
  '5e8d729a-e39b-41d6-9625-fbd62ab4d072',
  '8ac23cf2-ed78-4cec-9c86-57d9d88f5728',
  'c308b1f5-6893-4da6-85ae-222cabc53d13'}}

In [ ]:
dd.get_cols(o)

['record_id',
 'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str']

In [ ]:
import itertools
cols = []
for a, b in itertools.product(range(1, 5, 1), ['a', 'b']):
    cols.append(str(a) + b)

cols

['1a', '1b', '2a', '2b', '3a', '3b', '4a', '4b']

In [ ]:
# Quick test for the compute_bitarray.
# We expect to get 0b1010
row = {
    'record_id_a': 'abc',
    'record_id_b': 'abc',  
    
    # 1010
    '1a': 1, 
    '2a': 0, 
    '3a': 0, 
    '4a': 0,

    # 1111 
    '1b': 1, 
    '2b': 1, 
    '3b': 1, 
    '4b':1 
}

bits = (len(row) - 2) // 2
print(bits)

# comparison should give: 1010
# expect: 0b0101
ba = dd.compute_bitarray(row)
print(bin(ba))

num_ones =  dd.brian_kernighan(ba)
print(num_ones)

num_zeros = dd.count_unpadded_zero_bits(ba)
print(num_zeros) # gives 1

print(dd.count_unpadded_zero_bits(4)) # should give 2

# So, the actual way we want to get the number of 1's and 0's 
# in our computed bit array:
print(f"This is our bitarray: {bin(ba)}")

print(f"{dd.brian_kernighan(ba)} column(s) agreed.")
print(f"{dd.count_zero_bits(ba, dd.row2num_bits(row))} column(s) differed.")

4
0b1
1
0
2
This is our bitarray: 0b1
1 column(s) agreed.
3 column(s) differed.