In [25]:
import diffolars.diff as dd
from diffolars.demo import get_df_pair

In [26]:
dfs = get_df_pair(10, 10, n_new_cols=5, n_new_rows=5)
o = dfs['original']
m = dfs['mutated']

Generating initial dataset with 10 rows and 10 columns.
Generated mutated dataset.

In [27]:
dd.column_intercept(o, m)

{'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str',
 'record_id'}

In [28]:
dd.report_prune(o, m)

{'date_pruned': datetime.datetime(2026, 7, 2, 22, 45, 58, 414063),
 'cols_only_in_prev_load': 'No exclusives',
 'num_rows_only_in_prev_load': 0,
 'cols_only_in_latest_load': 'col_11_str , col_12_float , col_10_int , col_13_datetime , col_14_int',
 'num_rows_only_in_latest_load': 5}

In [29]:
dd.pruned_rows(o, m)

Found 0 rows unique to the current (original) table.
Found 0 rows unique to the next (latest) table.

shape: (5, 3)
┌────────────────────────────┬─────────────────┬─────────────────────────────────┐
│ date_pruned                ┆ source_dataload ┆ record_id                       │
│ ---                        ┆ ---             ┆ ---                             │
│ datetime[μs]               ┆ str             ┆ str                             │
╞════════════════════════════╪═════════════════╪═════════════════════════════════╡
│ 2026-07-02 22:45:58.425501 ┆ latest load     ┆ 9e3ca785-5931-48e9-b066-62365e… │
│ 2026-07-02 22:45:58.425501 ┆ latest load     ┆ 94dc391c-5097-49bd-8d2b-ff9a23… │
│ 2026-07-02 22:45:58.425501 ┆ latest load     ┆ 0a15175e-382d-428d-af26-da4fe4… │
│ 2026-07-02 22:45:58.425501 ┆ latest load     ┆ 3cf3ee7b-c231-416c-9925-0f1ee7… │
│ 2026-07-02 22:45:58.425501 ┆ latest load     ┆ 34936f55-6858-4105-9966-1d7e93… │
└────────────────────────────┴─────────────────┴─────────────────────────────────┘

In [30]:
dd.get_core(o, m)

['col_0_int', 'col_1_str', 'col_2_float', 'col_3_datetime', 'col_4_int', 'col_5_str', 'col_6_float', 'col_7_datetime', 'col_8_int', 'col_9_str']

shape: (10, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ col_0_int ┆ col_1_str ┆ col_2_flo ┆ … ┆ col_6_flo ┆ col_7_dat ┆ col_8_int ┆ col_9_st │
│ ---       ┆ ---       ┆ ---       ┆ at        ┆   ┆ at        ┆ etime     ┆ ---       ┆ r        │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ datetime[ ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 16ea95ee- ┆ 622164    ┆ nwExDKLmp ┆ 167852.98 ┆ … ┆ -778947.8 ┆ 2002-11-0 ┆ 594185    ┆ UzgYnuaC │
│ 2c9b-4a2c ┆           ┆ p         ┆ 0003      ┆   ┆ 51803     ┆ 6         ┆           ┆ cG       │
│ -a736-1ae ┆           ┆           ┆           ┆   ┆           ┆ 15:15:22  ┆           ┆          │
│ 971…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3a277588- ┆ 812001    ┆ zrsWdMLcP ┆ 807536.20 ┆ … ┆ 593982.63 ┆ 2014-04-1 ┆ 179022    ┆ ArqCihAG │
│ dcbf-4c33 ┆           ┆ k         ┆ 9943      ┆   ┆ 6678      ┆ 2         ┆           ┆ hE       │
│ -9b55-4e7 ┆           ┆           ┆           ┆   ┆           ┆ 05:14:17  ┆           ┆          │
│ 19b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 33b82a0a- ┆ -702231   ┆ UzDyzoLdZ ┆ -550426.6 ┆ … ┆ -738921.9 ┆ 2001-08-0 ┆ 584919    ┆ homVsifs │
│ 65bd-4500 ┆           ┆ I         ┆ 81867     ┆   ┆ 07514     ┆ 7         ┆           ┆ bs       │
│ -89fd-f85 ┆           ┆           ┆           ┆   ┆           ┆ 17:16:23  ┆           ┆          │
│ ee0…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1b1a88f8- ┆ 369189    ┆ dFsWYtWmh ┆ -413336.1 ┆ … ┆ 160118.86 ┆ 2000-02-2 ┆ 499680    ┆ WKOENJmd │
│ dcc8-4c86 ┆           ┆ c         ┆ 12689     ┆   ┆ 5435      ┆ 7         ┆           ┆ iQ       │
│ -8a56-eae ┆           ┆           ┆           ┆   ┆           ┆ 19:48:14  ┆           ┆          │
│ 987…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4b3778c6- ┆ -595408   ┆ OSYlWWgXc ┆ 197895.88 ┆ … ┆ -691569.6 ┆ 2013-10-1 ┆ -149964   ┆ PFkAAnFx │
│ 4907-4b90 ┆           ┆ h         ┆ 9746      ┆   ┆ 89667     ┆ 7         ┆           ┆ Rb       │
│ -8bb3-8bb ┆           ┆           ┆           ┆   ┆           ┆ 09:28:14  ┆           ┆          │
│ be1…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ afdbef95- ┆ -461440   ┆ pdrppmhLw ┆ -500825.3 ┆ … ┆ 771213.99 ┆ 2004-08-0 ┆ -540062   ┆ dvrRewdr │
│ aab6-43b7 ┆           ┆ U         ┆ 84519     ┆   ┆ 0455      ┆ 7         ┆           ┆ Ln       │
│ -9f37-a7f ┆           ┆           ┆           ┆   ┆           ┆ 06:22:35  ┆           ┆          │
│ 6b1…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ aac4e21e- ┆ 698434    ┆ QEZohRjfc ┆ 923493.64 ┆ … ┆ -748758.6 ┆ 2021-05-1 ┆ 134118    ┆ iJLZPgmi │
│ 6052-4b9d ┆           ┆ B         ┆ 362       ┆   ┆ 93422     ┆ 9         ┆           ┆ LM       │
│ -98f3-884 ┆           ┆           ┆           ┆   ┆           ┆ 06:08:30  ┆           ┆          │
│ 9e6…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 58423d1d- ┆ -633158   ┆ PrrRNiLnc ┆ -144872.0 ┆ … ┆ 609132.40 ┆ 2006-08-0 ┆ -950130   ┆ vMuNLXoA │
│ bb5b-49a3 ┆           ┆ k         ┆ 7738      ┆   ┆ 4435      ┆ 6         ┆           ┆ KB       │
│ -a476-fba ┆           ┆           ┆           ┆   ┆           ┆ 02:45:02  ┆           ┆          │
│ 8a8…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7bbfcc9f- ┆ 37908     ┆ qWXeFlMFd ┆ 875813.35 ┆ … ┆ 749470.91 ┆ 2011-01-0 ┆ 458610    ┆ XjwsMRpm │
│ a82e-4921 ┆           ┆ G         ┆ 6753      ┆   ┆ 7197      ┆ 7         ┆           ┆ SI       │
│ -9c42-511 ┆           ┆           ┆           ┆   ┆           ┆ 08:47:29  ┆           ┆          │
│ b80…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ceaeb000- ┆ 702211    ┆ tBGEhCiUN ┆ 858976.06 ┆ … ┆ -366895.6 ┆ 2007-05-0 ┆ -793392   ┆ juXdPTqF │
│ 3127-4bcb ┆           ┆ y         ┆ 3123      ┆   ┆ 81131     ┆ 9         ┆           ┆ yV       │
│ -8467-67b ┆           ┆           ┆           ┆   ┆           ┆ 06:10:05  ┆           ┆          │
│ 7e8…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
csd=dd.column_symmetric_diff(o, m)
csd

{'prev_load': set(),
 'latest_load': {'col_10_int',
  'col_11_str',
  'col_12_float',
  'col_13_datetime',
  'col_14_int'}}

In [32]:
dd.row_intercept(o, m)

{'16ea95ee-2c9b-4a2c-a736-1ae971cf2269',
 '1b1a88f8-dcc8-4c86-8a56-eae9873d2809',
 '33b82a0a-65bd-4500-89fd-f85ee0c54f52',
 '3a277588-dcbf-4c33-9b55-4e719b759723',
 '4b3778c6-4907-4b90-8bb3-8bbbe1fe054f',
 '58423d1d-bb5b-49a3-a476-fba8a87aba42',
 '7bbfcc9f-a82e-4921-9c42-511b800bfb56',
 'aac4e21e-6052-4b9d-98f3-8849e6e587d2',
 'afdbef95-aab6-43b7-9f37-a7f6b18255e9',
 'ceaeb000-3127-4bcb-8467-67b7e8c92ac6'}

In [33]:
dd.row_symmetric_diff(o, m)

{'prev_load': set(),
 'latest_load': {'0a15175e-382d-428d-af26-da4fe4006d7e',
  '34936f55-6858-4105-9966-1d7e9308f86e',
  '3cf3ee7b-c231-416c-9925-0f1ee7b541f5',
  '94dc391c-5097-49bd-8d2b-ff9a23bb2e09',
  '9e3ca785-5931-48e9-b066-62365e09d78b'}}

In [34]:
dd.get_cols(o)

['record_id',
 'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str']