In [16]:
import diffolars.diff as dd
from diffolars.demo import get_df_pair

In [ ]:
dfs = get_df_pair(10, 10, n_new_cols=5, n_new_rows=5, coverage=0.5)
o = dfs['original']
m = dfs['mutated']

Generating initial dataset with 10 rows and 10 columns.
Generated mutated dataset.

In [18]:
dd.column_intercept(o, m)

{'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str',
 'record_id'}

In [19]:
dd.report_prune(o, m)

{'date_pruned': datetime.datetime(2026, 7, 3, 12, 34, 44, 565495),
 'cols_only_in_prev_load': 'No exclusives',
 'num_rows_only_in_prev_load': 0,
 'cols_only_in_latest_load': 'col_11_str , col_10_int , col_12_float , col_14_int , col_13_datetime',
 'num_rows_only_in_latest_load': 5}

In [20]:
dd.pruned_rows(o, m)

Found 0 rows unique to the current (original) table.
Found 5 rows unique to the next (latest) table.

shape: (5, 3)
┌────────────────────────────┬─────────────────┬─────────────────────────────────┐
│ date_pruned                ┆ source_dataload ┆ record_id                       │
│ ---                        ┆ ---             ┆ ---                             │
│ datetime[μs]               ┆ str             ┆ str                             │
╞════════════════════════════╪═════════════════╪═════════════════════════════════╡
│ 2026-07-03 12:34:44.576746 ┆ latest load     ┆ d0822af7-20eb-4b9e-bd1d-d8f3f9… │
│ 2026-07-03 12:34:44.576746 ┆ latest load     ┆ 5ef0a644-ef42-4905-ba42-a7fd5d… │
│ 2026-07-03 12:34:44.576746 ┆ latest load     ┆ e79002a0-256f-4802-abf7-50a8bb… │
│ 2026-07-03 12:34:44.576746 ┆ latest load     ┆ 4d662ed2-49c8-4c32-aee7-8cbda1… │
│ 2026-07-03 12:34:44.576746 ┆ latest load     ┆ f9e65f73-f3c2-47d1-b446-98de5f… │
└────────────────────────────┴─────────────────┴─────────────────────────────────┘

In [21]:
oc, mc = dd.get_core(o, m)

In [22]:
oc

shape: (10, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ col_0_int ┆ col_1_str ┆ col_2_flo ┆ … ┆ col_6_flo ┆ col_7_dat ┆ col_8_int ┆ col_9_st │
│ ---       ┆ ---       ┆ ---       ┆ at        ┆   ┆ at        ┆ etime     ┆ ---       ┆ r        │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ datetime[ ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 434affa3- ┆ -728224   ┆ OeklVLhoz ┆ -36503.80 ┆ … ┆ 590219.74 ┆ 2024-10-1 ┆ 181166    ┆ DtKNsUJm │
│ aa59-4bb2 ┆           ┆ o         ┆ 5282      ┆   ┆ 1145      ┆ 3         ┆           ┆ SB       │
│ -95d6-e4b ┆           ┆           ┆           ┆   ┆           ┆ 19:00:07  ┆           ┆          │
│ 43d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4a8d80a- ┆ -586319   ┆ FORGnCIpg ┆ -299848.4 ┆ … ┆ 214395.45 ┆ 2001-11-2 ┆ 680063    ┆ TEpuKYAD │
│ 92c7-4af0 ┆           ┆ W         ┆ 53564     ┆   ┆ 8736      ┆ 0         ┆           ┆ Qi       │
│ -a695-925 ┆           ┆           ┆           ┆   ┆           ┆ 05:18:48  ┆           ┆          │
│ 2fb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 86531722- ┆ 149428    ┆ HiIsQYKxs ┆ -718024.1 ┆ … ┆ -547541.0 ┆ 2001-06-0 ┆ 212798    ┆ uNIaPqyE │
│ a44b-416a ┆           ┆ x         ┆ 34449     ┆   ┆ 478       ┆ 1         ┆           ┆ sn       │
│ -80d9-8af ┆           ┆           ┆           ┆   ┆           ┆ 02:25:39  ┆           ┆          │
│ a2d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9d376183- ┆ 584959    ┆ KnRCeBPTv ┆ -678328.6 ┆ … ┆ 287142.75 ┆ 2004-07-2 ┆ -33250    ┆ FInTFcyl │
│ 2837-4067 ┆           ┆ J         ┆ 57742     ┆   ┆ 894       ┆ 7         ┆           ┆ IO       │
│ -84e4-2fa ┆           ┆           ┆           ┆   ┆           ┆ 14:42:30  ┆           ┆          │
│ 6b2…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3a3b26fd- ┆ -851702   ┆ gFkSfrqFw ┆ -769374.2 ┆ … ┆ 73221.776 ┆ 2008-12-1 ┆ 886663    ┆ wIcKDQnO │
│ 50a6-496f ┆           ┆ O         ┆ 03383     ┆   ┆ 965       ┆ 3         ┆           ┆ tn       │
│ -8823-0d3 ┆           ┆           ┆           ┆   ┆           ┆ 02:22:55  ┆           ┆          │
│ a81…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9eafd3bf- ┆ 803430    ┆ yEcuuQMmm ┆ 965300.54 ┆ … ┆ 430880.83 ┆ 2005-01-1 ┆ 776453    ┆ keCbnSRo │
│ e808-4892 ┆           ┆ C         ┆ 1481      ┆   ┆ 8392      ┆ 7         ┆           ┆ Vg       │
│ -9640-302 ┆           ┆           ┆           ┆   ┆           ┆ 13:31:24  ┆           ┆          │
│ e88…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f0b1e1eb- ┆ -337036   ┆ rPYBNuWyp ┆ 360718.58 ┆ … ┆ 157530.04 ┆ 2006-08-2 ┆ -745563   ┆ NEwaHXzj │
│ 3e0e-40d1 ┆           ┆ e         ┆ 4146      ┆   ┆ 101       ┆ 2         ┆           ┆ mo       │
│ -92b3-3e0 ┆           ┆           ┆           ┆   ┆           ┆ 01:58:11  ┆           ┆          │
│ adf…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c14e00a3- ┆ -476392   ┆ MdogMzzBU ┆ 551185.18 ┆ … ┆ -98172.23 ┆ 2020-05-0 ┆ 96760     ┆ zUUQvGLM │
│ 3bfb-4703 ┆           ┆ B         ┆ 1377      ┆   ┆ 0758      ┆ 9         ┆           ┆ uP       │
│ -9115-995 ┆           ┆           ┆           ┆   ┆           ┆ 06:14:14  ┆           ┆          │
│ d61…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a923fc7d- ┆ 195883    ┆ EYEWMTbJj ┆ 259259.47 ┆ … ┆ -394295.2 ┆ 2024-03-2 ┆ 661933    ┆ VmCScZiD │
│ ff4b-4f15 ┆           ┆ m         ┆ 5044      ┆   ┆ 91058     ┆ 1         ┆           ┆ gO       │
│ -a1a0-3e3 ┆           ┆           ┆           ┆   ┆           ┆ 01:16:23  ┆           ┆          │
│ d35…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11cac988- ┆ 8996      ┆ HQKzFxhUl ┆ -257090.9 ┆ … ┆ 764580.87 ┆ 2011-07-0 ┆ 842338    ┆ AajYzpzD │
│ 05c4-4259 ┆           ┆ o         ┆ 16541     ┆   ┆ 7923      ┆ 9         ┆           ┆ TF       │
│ -81de-e6f ┆           ┆           ┆           ┆   ┆           ┆ 01:51:36  ┆           ┆          │
│ 17b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [23]:
mc

shape: (10, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ record_id ┆ col_0_int ┆ col_1_str ┆ col_2_flo ┆ … ┆ col_6_flo ┆ col_7_dat ┆ col_8_int ┆ col_9_st │
│ ---       ┆ ---       ┆ ---       ┆ at        ┆   ┆ at        ┆ etime     ┆ ---       ┆ r        │
│ str       ┆ i64       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆ f64       ┆ datetime[ ┆           ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆ μs]       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 434affa3- ┆ -727493   ┆ OeklVLhoz ┆ -37469.44 ┆ … ┆ 589604.36 ┆ 2024-10-1 ┆ 182014    ┆ DtKNsUJm │
│ aa59-4bb2 ┆           ┆ oRaUVv    ┆ 213       ┆   ┆ 94        ┆ 3         ┆           ┆ SBBWveR  │
│ -95d6-e4b ┆           ┆           ┆           ┆   ┆           ┆ 11:00:26  ┆           ┆          │
│ 43d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c4a8d80a- ┆ -586522   ┆ FORGnCIpg ┆ -300567.1 ┆ … ┆ 215268.13 ┆ 2001-11-1 ┆ 679533    ┆ TEpuKYAD │
│ 92c7-4af0 ┆           ┆ WUuZOF    ┆ 4509      ┆   ┆ 8445      ┆ 9         ┆           ┆ QidvHcT  │
│ -a695-925 ┆           ┆           ┆           ┆   ┆           ┆ 09:32:14  ┆           ┆          │
│ 2fb…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 86531722- ┆ 149774    ┆ HiIsQYKxs ┆ -718810.5 ┆ … ┆ -546904.3 ┆ 2001-05-3 ┆ 213358    ┆ uNIaPqyE │
│ a44b-416a ┆           ┆ xiHMcU    ┆ 92814     ┆   ┆ 77636     ┆ 1         ┆           ┆ snbcHsU  │
│ -80d9-8af ┆           ┆           ┆           ┆   ┆           ┆ 18:32:49  ┆           ┆          │
│ a2d…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9d376183- ┆ 585668    ┆ KnRCeBPTv ┆ -678126.8 ┆ … ┆ 287658.47 ┆ 2004-07-2 ┆ -32818    ┆ FInTFcyl │
│ 2837-4067 ┆           ┆ JZQCPX    ┆ 7951      ┆   ┆ 1558      ┆ 8         ┆           ┆ IOUMBbK  │
│ -84e4-2fa ┆           ┆           ┆           ┆   ┆           ┆ 17:14:11  ┆           ┆          │
│ 6b2…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3a3b26fd- ┆ -851924   ┆ gFkSfrqFw ┆ -768948.7 ┆ … ┆ 73714.168 ┆ 2008-12-1 ┆ 886074    ┆ wIcKDQnO │
│ 50a6-496f ┆           ┆ OOHXea    ┆ 33302     ┆   ┆ 318       ┆ 3         ┆           ┆ tnMzMch  │
│ -8823-0d3 ┆           ┆           ┆           ┆   ┆           ┆ 06:44:43  ┆           ┆          │
│ a81…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9eafd3bf- ┆ 803270    ┆ yEcuuQMmm ┆ 965254.20 ┆ … ┆ 430058.19 ┆ 2005-01-1 ┆ 776020    ┆ keCbnSRo │
│ e808-4892 ┆           ┆ CzFNmT    ┆ 0566      ┆   ┆ 9536      ┆ 8         ┆           ┆ VgwCmSy  │
│ -9640-302 ┆           ┆           ┆           ┆   ┆           ┆ 06:23:23  ┆           ┆          │
│ e88…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ f0b1e1eb- ┆ -336219   ┆ rPYBNuWyp ┆ 360680.04 ┆ … ┆ 157610.13 ┆ 2006-08-2 ┆ -744885   ┆ NEwaHXzj │
│ 3e0e-40d1 ┆           ┆ egGDeH    ┆ 2667      ┆   ┆ 8588      ┆ 1         ┆           ┆ moFiLAq  │
│ -92b3-3e0 ┆           ┆           ┆           ┆   ┆           ┆ 16:23:09  ┆           ┆          │
│ adf…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ c14e00a3- ┆ -477391   ┆ MdogMzzBU ┆ 551569.47 ┆ … ┆ -98174.34 ┆ 2020-05-0 ┆ 96664     ┆ zUUQvGLM │
│ 3bfb-4703 ┆           ┆ BllXYw    ┆ 085       ┆   ┆ 6067      ┆ 8         ┆           ┆ uPDSLYT  │
│ -9115-995 ┆           ┆           ┆           ┆   ┆           ┆ 12:07:23  ┆           ┆          │
│ d61…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ a923fc7d- ┆ 196665    ┆ EYEWMTbJj ┆ 259249.44 ┆ … ┆ -394876.2 ┆ 2024-03-2 ┆ 662607    ┆ VmCScZiD │
│ ff4b-4f15 ┆           ┆ mfsjQt    ┆ 649       ┆   ┆ 31441     ┆ 0         ┆           ┆ gOeaVYp  │
│ -a1a0-3e3 ┆           ┆           ┆           ┆   ┆           ┆ 23:03:06  ┆           ┆          │
│ d35…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 11cac988- ┆ 8152      ┆ HQKzFxhUl ┆ -257037.8 ┆ … ┆ 765290.28 ┆ 2011-07-0 ┆ 841947    ┆ AajYzpzD │
│ 05c4-4259 ┆           ┆ onaNIz    ┆ 66073     ┆   ┆ 8154      ┆ 9         ┆           ┆ TFaciPL  │
│ -81de-e6f ┆           ┆           ┆           ┆   ┆           ┆ 17:40:44  ┆           ┆          │
│ 17b…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [24]:
csd=dd.column_symmetric_diff(o, m)
csd

{'prev_load': set(),
 'latest_load': {'col_10_int',
  'col_11_str',
  'col_12_float',
  'col_13_datetime',
  'col_14_int'}}

In [25]:
dd.row_intercept(o, m)

{'11cac988-05c4-4259-81de-e6f17bb837af',
 '3a3b26fd-50a6-496f-8823-0d3a814a4dfb',
 '434affa3-aa59-4bb2-95d6-e4b43d436b1b',
 '86531722-a44b-416a-80d9-8afa2dd52e0b',
 '9d376183-2837-4067-84e4-2fa6b284e494',
 '9eafd3bf-e808-4892-9640-302e887c2e06',
 'a923fc7d-ff4b-4f15-a1a0-3e3d35bdbce8',
 'c14e00a3-3bfb-4703-9115-995d61f636e7',
 'c4a8d80a-92c7-4af0-a695-9252fb15e93a',
 'f0b1e1eb-3e0e-40d1-92b3-3e0adf00e75f'}

In [26]:
dd.row_symmetric_diff(o, m)

{'prev_load': set(),
 'latest_load': {'4d662ed2-49c8-4c32-aee7-8cbda1517037',
  '5ef0a644-ef42-4905-ba42-a7fd5d184b11',
  'd0822af7-20eb-4b9e-bd1d-d8f3f9304e22',
  'e79002a0-256f-4802-abf7-50a8bb148772',
  'f9e65f73-f3c2-47d1-b446-98de5fe061ef'}}

In [27]:
dd.get_cols(o)

['record_id',
 'col_0_int',
 'col_1_str',
 'col_2_float',
 'col_3_datetime',
 'col_4_int',
 'col_5_str',
 'col_6_float',
 'col_7_datetime',
 'col_8_int',
 'col_9_str']